const NOTIFICATION_TYPES = {
  COMPLAINT_CREATED: 'COMPLAINT_CREATED',
  WORKER_ASSIGNED: 'WORKER_ASSIGNED',
  WORK_COMPLETED: 'WORK_COMPLETED',
  VERIFIED: 'VERIFIED',
  CLOSED: 'CLOSED',
  USER_REGISTERED: 'USER_REGISTERED',
  WORKER_CREATED: 'WORKER_CREATED',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
};

module.exports = NOTIFICATION_TYPES;
