const STATUSES = {
  NEW: 'NEW',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED_BY_WORKER: 'COMPLETED_BY_WORKER',
  REWORK_REQUIRED: 'REWORK_REQUIRED',
  VERIFIED_BY_ADMIN: 'VERIFIED_BY_ADMIN',
  CLOSED: 'CLOSED',
};

const VALID_TRANSITIONS = {
  NEW: ['UNDER_REVIEW', 'ASSIGNED', 'IN_PROGRESS'],
  UNDER_REVIEW: ['ASSIGNED', 'REWORK_REQUIRED'],
  ASSIGNED: ['IN_PROGRESS', 'UNDER_REVIEW'],
  IN_PROGRESS: ['COMPLETED_BY_WORKER', 'ASSIGNED'],
  COMPLETED_BY_WORKER: ['VERIFIED_BY_ADMIN', 'REWORK_REQUIRED'],
  REWORK_REQUIRED: ['IN_PROGRESS', 'ASSIGNED'],
  VERIFIED_BY_ADMIN: ['CLOSED', 'REWORK_REQUIRED'],
  CLOSED: [],
};

const isValidTransition = (from, to) => {
  const allowed = VALID_TRANSITIONS[from] || [];
  return allowed.includes(to);
};

module.exports = { STATUSES, VALID_TRANSITIONS, isValidTransition };
