const STATUSES = {
  NEW: 'NEW',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED_BY_WORKER: 'COMPLETED_BY_WORKER',
  REWORK_REQUIRED: 'REWORK_REQUIRED',
  VERIFIED_BY_ADMIN: 'VERIFIED_BY_ADMIN',
  CLOSED: 'CLOSED',
};

module.exports = STATUSES;
